In [5]:
import os
import pandas as pd
import numpy as np
import geocoder
import feather
import re
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GroupKFold
from tqdm import tqdm_notebook as tqdm

In [6]:
FOLDS_PATH = "../input/mynavi_Stratifiedfold01.feather"
train = feather.read_dataframe(FOLDS_PATH)
n_train = len(train)
target = train["賃料"]
test = pd.read_csv('../input/test.csv')

train_length = train.shape[0]
test_length = test.shape[0]
all_df = pd.concat([train, test], axis=0, ignore_index=True)


access = feather.read_dataframe("../code/feature_csv/access_feature.feather")
all_df = pd.concat([all_df, access], axis=1)
base = feather.read_dataframe("../code/feature_csv/base_feature1.feather")
all_df = pd.concat([all_df, base], axis=1)

org_columns = all_df.columns

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [7]:
def modify_miss(df_input):
    df_input.loc[df_input["間取り"].str.contains("11R"), "間取り"] = "1R"
    
    df_input.loc[df_input["築年数"].str.contains("520年5ヶ月"), "築年数"] = "52年5ヶ月"
    
    df_input.loc[df_input["築年数"].str.contains("1019年7ヶ月"), "築年数"] = "19年7ヶ月"
    
    df_input.loc[df_input["面積"].str.contains("430.1m2"), "面積"] = "43.01m2"
    #idx = df_input["築年数"].str.contains("1019年7ヶ月")
    #df_input["築年数"][idx] = "19年7ヶ月"    
    
    "三田線 三田(兵庫県)駅 徒歩14分"
    
    return df_input

def modify_rent(target, df_input):
    """ id == 5776 で賃料の0が一つ多い"""
    target = np.where(df_input["id"]==5776, 120350, target)
    
    return target

all_df = modify_miss(all_df)

In [8]:
org_columns.values

array(['fold_id', 'id', 'アクセス', 'キッチン', 'バス・トイレ', '周辺環境', '契約期間', '室内設備',
       '建物構造', '所在地', '所在階', '放送・通信', '方角', '築年数', '賃料', '間取り', '面積',
       '駐車場', '路線_0', '駅_0', '駅からの距離_0', '路線_1', '駅_1', '駅からの距離_1',
       '路線_2', '駅_2', '駅からの距離_2', '駅_0からの距離_mean', '駅_0からの距離_std',
       '駅_0からの距離_min', '駅_0からの距離_max', '駅_1からの距離_mean', '駅_1からの距離_std',
       '駅_1からの距離_min', '駅_1からの距離_max', '駅_2からの距離_mean', '駅_2からの距離_std',
       '駅_2からの距離_min', '駅_2からの距離_max', '路線_0_counts', '路線_1_counts',
       '路線_2_counts', '駅_0_counts', '駅_1_counts', '駅_2_counts',
       '路線_counts_max', '路線_counts_mean', '路線_counts_min',
       '路線_counts_std', '駅_counts_max', '駅_counts_mean', '駅_counts_min',
       '駅_counts_std', '距離_max', '距離_min', '距離_mean', '距離_std',
       '路線_0_counts/距離', '路線_1_counts/距離', '路線_2_counts/距離',
       '駅_0_counts/距離', '駅_1_counts/距離', '駅_2_counts/距離',
       '路線counts/距離_max', '路線counts/距離_mean', '路線counts/距離_min',
       '路線counts/距離_std', '駅counts/距離_max', '駅counts/距離_mean',
       '駅counts/距離_min', '駅counts/距離_std', '駅_0からの距離_mean_diff',
       '駅_1からの距離_mean_diff', '駅_2からの距離_mean_diff', 'access_way_count',
       '駅_0_緯度', '駅_0_経度', '駅_1_緯度', '駅_1_経度', '駅_2_緯度', '駅_2_経度',
       'catuse_駅_0', 'catuse_路線_0', 'int方角', 'num_of_NULL',
       '周辺環境_element_counts', '室内設備_element_counts',
       'バス・トイレ_element_counts', 'キッチン_element_counts',
       '放送・通信_element_counts', '設備和', 'count_num_of_NULL',
       'count_周辺環境_element_counts', 'count_室内設備_element_counts',
       'count_バス・トイレ_element_counts', 'count_キッチン_element_counts',
       'count_放送・通信_element_counts', 'count_設備和', 'count_所在地',
       'count_アクセス', 'count_間取り', 'count_築年数', 'count_方角', 'count_面積',
       'count_所在階', 'count_バス・トイレ', 'count_キッチン', 'count_放送・通信',
       'count_室内設備', 'count_駐車場', 'count_周辺環境', 'count_建物構造',
       'count_契約期間', 'float面積', '新築', 'int築年', 'int築月', '築月数',
       'count_int築年', 'count_int築月', 'count_築月数', '所在_区', '所在_区_count',
       '地域名', 'count_地域名', '地域_n丁目', 'count_地域_n丁目', '区_GMM0', '区_GMM1',
       '区_GMM2', 'living_floor', '一戸建て', 'building_floor',
       'cat_building_height', 'living/building', 'count_living_floor',
       'count_building_floor', 'count_cat_building_height',
       'count_living/building', 'int間取り', 'cat_int間取り', '納戸', '間取りtype',
       'count_int間取り', 'count_間取りtype', '定期借家', 'contract_period',
       'int建物構造', 'has_大学', 'has_郵便局', 'has_小学校', 'has_飲食店', 'has_総合病院',
       'has_スーパー', 'has_図書館', 'has_デパート', 'has_公園', 'has_コインパーキング',
       'has_クリーニング', 'has_幼稚園・保育園', 'has_月極駐車場', 'has_銀行', 'has_ドラッグストア',
       'has_レンタルビデオ', 'has_コンビニ', 'has_学校', 'has_病院',
       'num_of_facilities_type', '郵便局', '大学', '学校', '小学校', '飲食店', 'スーパー',
       '図書館', 'デパート', '公園', 'コインパーキング', 'レンタルビデオ', 'クリーニング', '幼稚園・保育園',
       '銀行', 'ドラッグストア', '月極駐車場', 'コンビニ', '総合病院', '病院', 'min_facilities',
       'max_facilities', 'mean_facilities', 'std_facilities'],
      dtype=object)

In [6]:
train = all_df[:n_train]
test = all_df[n_train:]
train_y = train["賃料"]
folds = train["fold_id"]
train_y = modify_rent(train_y, train)

In [7]:
"""for i in tqdm(range(folds.nunique())):
    tr_x, va_x = train[train["fold_id"]!=i].copy(), train[train["fold_id"]==i].copy()
    tr_y, va_y = train_y[train["fold_id"]!=i].copy(), train_y[train["fold_id"]==i].copy()
    
    tr_x = tr_x.reset_index(drop=True)
    skf_encoding = StratifiedKFold(n_splits=4, shuffle=True, random_state=100)
    tr_x["foldINfold_id"] = np.nan
    
    for i, (train_index, valid_index) in enumerate(skf_encoding.split(tr_x["id"], tr_x["アクセス"])):
        tr_x.loc[valid_index, "foldINfold_id"] = i"""
        #target_mean = data_tmp.iloc[train_index].groupby(column)[target].mean()
        #tmp[valid_index] = tr_x[column].iloc[valid_index].map(target_mean)"""
        
        
"""folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=71)
df["fold_id"] = np.nan
for i, (train_index, valid_index) in enumerate(folds.split(df["id"], df["アクセス"])):
    df.loc[valid_index, "fold_id"] = i

df.to_feather("../../input/mynavi_Stratifiedfold_access_n4.feather")"""

'folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=71)\ndf["fold_id"] = np.nan\nfor i, (train_index, valid_index) in enumerate(folds.split(df["id"], df["アクセス"])):\n    df.loc[valid_index, "fold_id"] = i\n\ndf.to_feather("../../input/mynavi_Stratifiedfold_access_n4.feather")'

In [7]:
target = "賃料"    #所在_区 での面積　あたりの値段
columns = ["所在_区", "間取りtype", 'catuse_路線_0', 'catuse_駅_0', 'アクセス',
           "cat_int間取り", "cat_building_height", 
          ]
stat = "mean"
how_to_make_in_fold = "group"
result = []
n_split = 4

for column in tqdm(columns):
    data_tmp = pd.DataFrame({column:train[column], target:train[target]})
    target_mean = data_tmp.groupby(column)[target].mean()
    test[column] = test[column].map(target_mean)

for i in tqdm(range(folds.nunique())):
    tr_x, va_x = train[train["fold_id"]!=i].copy(), train[train["fold_id"]==i].copy()
    tr_y, va_y = train_y[train["fold_id"]!=i].copy(), train_y[train["fold_id"]==i].copy()
    
    tr_x = tr_x.reset_index(drop=True)
    tr_y = tr_y.reset_index(drop=True)
    tr_x["foldINfold_id"] = np.nan
    if how_to_make_in_fold == "str":
        skf_encoding = StratifiedKFold(n_splits=4, shuffle=True, random_state=100)
        for i, (train_index, valid_index) in enumerate(skf_encoding.split(tr_x["id"], tr_x["アクセス"])):
            tr_x.loc[valid_index, "foldINfold_id"] = i
    
    if how_to_make_in_fold == "group":
        grp_encoding = GroupKFold(n_splits=4)
        for i, (train_index, valid_index) in enumerate(grp_encoding.split(tr_x["id"], tr_x["アクセス"], tr_x["id"])):
            tr_x.loc[valid_index, "foldINfold_id"] = i
    
    
    for column in columns:
        data_tmp = pd.DataFrame({column:tr_x[column], target:tr_y, "foldINfold":tr_x["foldINfold_id"]})
        target_mean = data_tmp.groupby(column)[target].mean()
        va_x.loc[:, column] = va_x[column].map(target_mean)
        #va_x[column] = va_x[column].map(target_mean) #これあかんのん？

        tmp = np.repeat(np.nan, tr_x.shape[0])

        for i in range(n_split):
            target_mean = data_tmp[tr_x["foldINfold_id"]!=i].groupby(column)[target].mean()
            tmp[tr_x["foldINfold_id"]==i] = tr_x[column][tr_x["foldINfold_id"]==i].map(target_mean)

        tr_x.loc[:, column] = tmp
    
    tmp = pd.concat([tr_x, va_x])
    result.append(tmp)
    

# merge:ver 1min 1s
# map:ver    4.28 s

HBox(children=(IntProgress(value=0, max=7), HTML(value='')))

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

HBox(children=(IntProgress(value=0, max=5), HTML(value='')))

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:47: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:47: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:47: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:47: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:47: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [8]:
output_dir = '../code/feature_csv/'

""" target encoding 後のtest保存 """
test.to_csv(os.path.join(output_dir, f'target_encoding_test.csv'), index = False)

""""""
for i in tqdm(range(folds.nunique())):
    if how_to_make_in_fold == "group":
        result[i] = result[i].sort_values("id")
        result[i][columns + ["id", "fold_id"]].to_csv(os.path.join(output_dir, f'target_encoding_groupfold{i}.csv'), index = False)
    
    if how_to_make_in_fold == "str":
        result[i] = result[i].sort_values("id")
        result[i][columns + ["id", "fold_id"]].to_csv(os.path.join(output_dir, f'target_encoding_strfold{i}.csv'), index = False)
    #f'../code/feature_csv/target_encoding_fold{i}.csv'

HBox(children=(IntProgress(value=0, max=5), HTML(value='')))

In [1]:
#result[0].sort_values("id")
"""a = result[4]
v = a[a["fold_id"]==0]
t = a[a["fold_id"]!=0][columns + ["id"]]
a[a["fold_id"]!=4]"""

'a = result[4]\nv = a[a["fold_id"]==0]\nt = a[a["fold_id"]!=0][columns + ["id"]]\na[a["fold_id"]!=4]'

In [64]:
t = t.sort_values("id")
#t.head(2)
#tt = all_df[all_df["fold_id"]==0]

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [62]:
#tt[columns + ["id"]]

In [2]:
test[columns].head()

NameError: name 'test' is not defined

In [20]:
tr_x["所在_区"]
target_mean
tmp
data_tmp
target_mean = data_tmp[tr_x["foldINfold_id"]!=i].groupby(column)[target].mean()
tmp[tr_x["foldINfold_id"]==i] = tr_x[column][tr_x["foldINfold_id"]==i].map(target_mean)
tmp

array([            nan,             nan,  79474.22758621, ...,
                   nan, 125676.92841163,             nan])

In [276]:
output_dir = '../code/feature_csv/'
columns = [col for col in columns if col not in ["定期借家", "一戸建て"]]
result[0][columns]

for i in range(folds.nunique()):
    result[i][columns].to_csv(os.path.join(output_dir, f'target_encoding_fold{i}.csv'), index = False)

In [24]:
train = all_df[:n_train]
test = all_df[n_train:]
train_y = train["賃料"]
folds = train["fold_id"]
target = "賃料" 
for column in columns:
    data_tmp = pd.DataFrame({column:train[column], target:train[target]})
    target_mean = data_tmp.groupby(column)[target].agg(stat)
    test[column] = test[column].map(target_mean)

/Users/ueda/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [20]:
test[columns].head()

,所在_区,int築年,間取りtype,catuse_路線_0,catuse_駅_0,cat_int間取り,cat_building_height
31470,113781.270261,80782.051282,183369.036838,124795.435393,125041.666667,147231.745687,137620.297947
31471,145674.389052,135242.034464,82776.981503,143593.856767,151232.222222,104948.426653,102852.057768
31472,110916.884343,109469.375000,90421.504777,89715.970516,103259.183673,104948.426653,102852.057768
31473,97708.174675,81129.147982,90421.504777,97878.972727,97172.303704,104948.426653,86710.188273
31474,97708.174675,90200.813008,183369.036838,97878.972727,97172.303704,147231.745687,102852.057768

In [9]:
#pd.concat([tr_x, va_x])

In [292]:
p = train[folds!=0]
p[columns] = result[0][columns]
p[columns]
#p.shape

,所在_区,int築年,間取りtype,catuse_路線_0,catuse_駅_0,cat_int間取り,cat_building_height
0,97076.182708,131680.781759,90537.953228,113174.117647,111734.482759,104412.398166,138134.772136
1,180539.274194,93244.645570,82482.526899,150378.212005,217490.384615,104412.398166,138134.772136
4,78882.649635,86216.709512,106185.530442,72640.625000,72529.411765,147879.828641,86442.136279
5,117028.482972,135720.059880,183579.461922,121948.076923,140840.579710,146585.889395,137612.273599
7,145811.940299,138783.615257,90477.066890,142777.097130,143465.833333,104605.980413,136873.925337
8,128690.851064,92104.651163,106212.154973,165831.428571,91825.925926,148162.160520,137530.084634
9,89902.564103,94958.139535,106212.154973,94678.645833,102389.534884,104526.106825,103163.776676
10,107163.439065,129173.140496,90451.761583,127989.958159,108180.412371,104661.709946,137612.273599
11,87213.000973,66500.000000,90477.066890,82390.505837,74171.875000,104605.980413,86370.839385
12,211414.427646,134774.488583,181892.954286,195383.597884,238931.818182,104605.980413,136873.925337
13,98198.840580,89278.000000,106214.508677,100031.083845,90352.040816,146225.931233,102886.688499
14,115078.151261,110979.753363,90520.885411,103774.005952,132565.040650,104526.106825,137530.084634
15,173154.630872,91002.012072,106212.154973,113344.910180,109703.125000,104526.106825,103163.776676
16,90014.330544,134558.413462,90537.953228,89218.816068,81216.417910,104412.398166,101995.119333
17,86007.899232,131680.781759,90537.953228,103044.787078,84177.631579,104412.398166,86442.136279
18,129897.284123,123642.339833,181892.954286,104629.767025,141437.500000,193552.979552,136873.925337
20,102732.896552,91681.481481,181892.954286,88220.814480,81710.526316,146225.931233,86370.839385
22,180539.274194,95672.757874,183742.206703,151802.535022,188406.779661,147879.828641,273200.055238
23,106693.586498,137170.125786,90477.066890,99397.082658,106613.548387,104605.980413,102886.688499
24,86007.899232,79661.764706,82482.526899,84988.709677,91470.588235,104412.398166,101995.119333
25,109803.177570,121052.255054,82401.656726,148928.272180,79363.636364,104605.980413,86370.839385
26,129109.515260,143498.621262,183579.461922,155487.772898,141804.878049,104661.709946,137612.273599
28,86007.899232,116833.212996,183742.206703,103044.787078,89846.666667,104412.398166,138134.772136
30,109452.862958,129901.808036,184605.793879,108000.000000,91040.540541,148162.160520,137530.084634
31,86227.997018,86083.910891,106212.154973,108210.974651,88002.551020,148162.160520,87347.515580
32,79127.412587,98096.970472,106212.154973,103774.005952,84005.815385,148162.160520,103163.776676
34,129897.284123,134774.488583,90477.066890,104629.767025,157204.201278,104605.980413,136873.925337
35,79809.938859,138783.615257,90477.066890,79647.285276,80888.636364,104605.980413,86370.839385
36,92500.770713,112316.066667,183579.461922,95474.092827,87657.575758,198429.438976,102972.279386
37,116525.149701,134774.488583,181892.954286,149077.660972,103780.000000,104605.980413,136873.925337
...,...,...,...,...,...,...,...
31429,179478.565737,144845.491803,184605.793879,155542.616646,216041.322314,104526.106825,280431.543893
31430,112514.822835,105668.018018,181892.954286,96751.457627,87521.084337,146225.931233,136873.925337
31432,114325.732829,125367.193676,90520.885411,117353.438819,114833.333333,104526.106825,87347.515580
31433,173647.652174,143498.621262,90451.761583,98817.944251,108342.056075,104661.709946,137612.273599
31434,100518.513324,134558.413462,82482.526899,97730.923469,100052.631579,104412.398166,101995.119333
31435,98874.425631,130866.110020,184605.793879,98116.822742,89769.767442,196524.755382,87347.515580
31438,86007.899232,91279.113924,82482.526899,103044.787078,82147.572816,104412.398166,86442.136279
31439,92707.671656,121052.255054,90477.066890,148928.272180,104807.717949,104605.980413,102886.688499
31440,90014.330544,145851.648352,183742.206703,113174.117647,78000.000000,104412.398166,101995.119333
31441,89902.564103,118208.602151,184605.793879,147029.509687,95510.869565,104526.106825,87347.515580
31442,92500.770713,135011.535726,82330.634711,95474.092827,96396.226415,104661.709946,86381.864872
31443,99029.962500,143498.621262,183579.461922,121375.241158,129135.714286,198429.438976,86381.864872
31445,85819.295297,86753.105590,183579.461922,85664.714567,76197.619048,198429.438976,102972.279386
31447,173154.630872,122659.117647,90520.885411,151686.257505,172320.967742,104526.106825,137530.084634
31448,92707.671656,127230.487805,82401.656726,95050.372340,93606.000000,104605.980413,86370.839385
31449,86227.997018,134465.235294,90520.885411,103058.333333,82953.424658,104526.106825,87347.515580
31452,116525.149701,121052.255054,90477.066890,120610.747331,98504.761905,104605.980413,102886.688499
31453,87213.000973,86840.468227,82401.656726,104017.478510,81915.306122,104605.980413,102886.688499
31454,179478.565737,129901.808036,90520.885411,156422.675585,159514.705882,104526.106825,137530.084634
31455,85762.249808,130300.192941,106214.508677,87432.956693,84017.241379,146225.931233,102886.688499
31456,180228.517110,117210.109170,181892.954286,113740.000000,145432.000000,104605.980413,136873.925337
31457,93058.446257,130241.650718,90537.953228,95349.056604,86092.063492,104412.398166,101995.119333
31458,126718.083425,129535.400908,90451.761583,103567.857143,112418.691589,104661.709946,102972.279386
31459,90179.750779,113975.511429,106387.084752,146589.565217,82590.476190,104661.709946,102972.279386
31461,179478.565737,134469.445833,90520.885411,210847.087379,164000.000000,104526.106825,137530.084634
31462,100518.513324,151663.747927,183742.206703,150378.212005,150239.726027,147879.828641,138134.772136
31463,126718.083425,122416.399287,183579.461922,146589.565217,193654.545455,146585.889395,137612.273599
31464,124820.898438,136238.008934,90520.885411,127734.511435,110235.483871,104526.106825,103163.776676
31467,124979.569677,93631.578947,106212.154973,108210.974651,105822.343750,196524.755382,103163.776676
31468,102732.896552,143912.297297,106214.508677,100031.083845,102793.859649,104605.980413,86370.839385

In [288]:
"""column = "アクセス"
targets = ['int面積','賃料']
for target in targets:
    for stat in stats:
        temp = all_df.groupby(column)[target].agg([stat]).rename({stat:f'{target}{stat}_of_{column}'},axis=1)
        all_df = pd.merge(all_df,temp,on=column,how='left')"""



#all_df["賃金/面積_mean_所在_区"] = all_df["賃料mean_of_所在_区"] / all_df["int面積mean_of_所在_区"]
#all_df["賃金/築年_mean_所在_区"] = all_df["賃料mean_of_所在_区"] / all_df["int築年mean_of_所在_区"]
#all_df["賃金mean/各築年_所在_区"] = all_df["賃料mean_of_所在_区"] / all_df["int築年"]

'column = "アクセス"\ntargets = [\'int面積\',\'賃料\']\nfor target in targets:\n    for stat in stats:\n        temp = all_df.groupby(column)[target].agg([stat]).rename({stat:f\'{target}{stat}_of_{column}\'},axis=1)\n        all_df = pd.merge(all_df,temp,on=column,how=\'left\')'

In [7]:
all_df.describe()

,id,賃料,駅からの距離_0,駅からの距離_1,駅からの距離_2,駅_0からの距離_mean,駅_0からの距離_std,駅_0からの距離_min,駅_0からの距離_max,駅_1からの距離_mean,...,contract_periodmax_of_一戸建て,平均contract_period_diff_一戸建て,平均contract_period_percent_一戸建て,contract_periodmean_of_cat_building_height,contract_periodstd_of_cat_building_height,contract_periodmin_of_cat_building_height,contract_periodmax_of_cat_building_height,平均contract_period_diff_cat_building_height,平均contract_period_percent_cat_building_height,面積/駅から距離
count,62732.00000,3.147000e+04,62732.000000,59747.000000,56117.000000,62732.000000,62730.000000,62732.00000,62732.000000,59747.000000,...,62732.000000,4.863100e+04,48631.000000,62732.000000,62732.000000,62732.000000,62732.000000,4.863100e+04,48631.000000,62732.000000
mean,31366.50000,1.182903e+05,642.244469,1057.015381,1392.325317,1027.759521,708.999390,98.02079,5983.633301,1006.042358,...,261.210993,2.162413e-16,1.024912,24.551271,4.835146,1.626506,229.439265,2.641651e-16,1.025009,0.088439
std,18109.31288,7.374880e+04,570.805374,920.751160,1204.006836,440.995422,568.599182,69.84346,5314.867188,482.329529,...,19.845522,4.965982e+00,0.311242,0.484042,1.233195,1.353819,63.604111,4.986726e+00,0.310803,0.102044
min,1.00000,2.500000e+04,80.000000,80.000000,80.000000,334.344818,113.137085,80.00000,720.000000,334.344818,...,120.000000,-2.395465e+02,0.092627,24.140916,3.380623,1.000000,72.000000,-2.398591e+02,0.091443,0.001606
25%,15683.75000,7.600000e+04,320.000000,640.000000,880.000000,766.866455,373.121124,80.00000,2000.000000,771.346680,...,264.000000,4.535352e-01,1.018897,24.140916,3.380623,1.000000,264.000000,1.409156e-01,1.005871,0.035000
50%,31366.50000,1.020000e+05,560.000000,880.000000,1200.000000,935.532654,477.276703,80.00000,2720.000000,918.087952,...,264.000000,4.535352e-01,1.018897,24.655270,5.078010,1.000000,264.000000,6.552700e-01,1.027303,0.057500
75%,47049.25000,1.360000e+05,800.000000,1200.000000,1600.000000,1128.098755,761.223633,80.00000,9680.000000,1098.288086,...,264.000000,4.535352e-01,1.018897,24.711958,5.823592,2.000000,264.000000,7.119576e-01,1.029665,0.102282
max,62732.00000,2.500000e+06,10960.000000,24240.000000,25600.000000,7330.500000,5931.688965,2960.00000,25600.000000,7330.500000,...,264.000000,2.520554e+01,24.453535,26.913318,8.256078,9.000000,264.000000,2.365527e+01,24.655270,2.747375

In [8]:
new_columns = [column for column in all_df.columns if column not in org_columns]

In [9]:
all_df_feature = all_df[new_columns]

In [10]:
#all_df_feature = all_df_feature.drop(['緯度経度', "count_id"], axis=1)
output_dir = '../code/feature_csv/'
all_df_feature.to_feather(os.path.join(output_dir, 'nonleak_group_feature2.feather'))

In [11]:
all_df_feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62732 entries, 0 to 62731
Columns: 163 entries, float面積mean_of_所在_区 to 面積/駅から距離
dtypes: float64(145), int64(18)
memory usage: 78.0 MB